export const REQUEST_SONG_BY_ID = 'REQUEST_SONG_BY_ID';
export const RECEIVE_SONG_BY_ID = 'RECEIVE_SONG_BY_ID';
export const ERROR_RECEIVE_SONG_BY_ID = 'ERROR_RECEIVE_SONG_BY_ID';
export const REQUEST_UPDATE_SONG = 'REQUEST_UPDATE_SONG';
export const RECEIVE_UPDATE_SONG = 'RECEIVE_UPDATE_SONG';
export const ERROR_RECEIVE_UPDATE_SONG = 'ERROR_RECEIVE_UPDATE_SONG';