export const REQUEST_CREATE_SONG = 'REQUEST_CREATE_SONG';
export const RECEIVE_CREATE_SONG = 'RECEIVE_CREATE_SONG';
export const ERROR_CREATE_SONG = 'ERROR_CREATE_SONG';
export const RESET_CREATE_SONG = 'RESET_CREATE_SONG';